project:
  name: oIBP
  company: 上海欧睿供应链管理有限公司
  website: http://www.o-ibp.com
  
server:
  port: 8080
  contextPath: /web
  session:
    timeout: 1800
  #ssl:
  #  key-store: classpath:keystore.p12
  #  key-store-password: 0-ibp2o17@web
  #  keyStoreType: PKCS12
  #  keyAlias: oibp_app

spring:
  profiles:
    active: uat_singleton
    
  #添加那个目录的文件需要restart
  #devtools:
  #   restart:
  #      additional-paths: src/main/java
  #      exclude: static/**,templates/**
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      resolve-lazily: false
      location:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  mvc:
    view:
      prefix: /WEB-INF/pages
      suffix: .jsp
    favicon:
      enabled: false
      
  datasource:
    druid:
      stat-view-servlet: 
        enabled: true
        url-pattern: /oibp/datasource/monitor/*
        login-username: oibp_druid
        login-password: 0ibp_dru1d
---
spring:
  profiles: dev_singleton
  redis:
    database: 0
    host: redis
    port: 6379
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10
      
project: 
  environment: dev
  runmode: singleton
  #runmode: saas
  singleton:
    #enterprise: xjzhou  #1.1.1
    enterprise: kpi_data
  checkDataEnable: false
  version: 1.2.2

datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.1.101:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&&useSSL=false&rewriteBatchedStatement=true
    url: jdbc:mysql://127.0.0.1:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    #url: jdbc:mysql://gz-cdb-bspxat6d.sql.tencentcdb.com:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: remoteuser
    password: RK0FnE7TsiZYHyLxpgJ8iIEtpW7eSnrYe370Y2Wy6XW62c9VpBvQGX7YwByE2Xp8iWdni8lg4b0V+VUZwZCXHQ==
    initialSize: 20
    minIdle: 20
    maxActive: 50
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAILqcyiEIU/xsognRHM+6PX17R0gb+AUgJ75aN+Pn08PNGgTf5Ni4ibD4xGRSZimFSiTut+5nBGE4xMdlBHvKT0CAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
    
sms:
  config:
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}
    product:
      id: 887362

logging:
  level:
    root: info

---
spring:
  profiles: dev_saas
  redis:
    database: 0
    host: redis
    port: 6379
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10

project:  
  environment: dev
  runmode: saas
  checkDataEnable: false
  version: 1.2.2

#oibp_core
datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: remoteuser
    password: RK0FnE7TsiZYHyLxpgJ8iIEtpW7eSnrYe370Y2Wy6XW62c9VpBvQGX7YwByE2Xp8iWdni8lg4b0V+VUZwZCXHQ==
    initialSize: 20
    minIdle: 20
    maxActive: 50
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAILqcyiEIU/xsognRHM+6PX17R0gb+AUgJ75aN+Pn08PNGgTf5Ni4ibD4xGRSZimFSiTut+5nBGE4xMdlBHvKT0CAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
    
sms:
  config:
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}
    product:
      id: 887362


logging:
  level:
    root: info

---
spring:
  profiles: tencent_singleton
  redis:
    database: 0
    host: redis
    port: 6379
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10

server:
  port: 8080
  
project:  
  environment: dev
  runmode: singleton
  singleton:
    #enterprise: pacificcoffee
    enterprise: drink3
  checkDataEnable: false
  version: 1.2.2

#oibp_core
datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.0.10:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: remoteuser
    password: RK0FnE7TsiZYHyLxpgJ8iIEtpW7eSnrYe370Y2Wy6XW62c9VpBvQGX7YwByE2Xp8iWdni8lg4b0V+VUZwZCXHQ==
    initialSize: 20
    minIdle: 20
    maxActive: 50
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAILqcyiEIU/xsognRHM+6PX17R0gb+AUgJ75aN+Pn08PNGgTf5Ni4ibD4xGRSZimFSiTut+5nBGE4xMdlBHvKT0CAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
    
sms:
  config:
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}
    product:
      id: 887362


logging:
  level:
    root: info
    
---
spring:
  profiles: uat_singleton
  redis:
    database: 0
    host: redis
    port: 6393
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10

server:
  port: 8782
  
project:  
  environment: uat
  runmode: singleton
  singleton:
    enterprise: xiaoxue
  checkDataEnable: false
  version: 1.2.2

#oibp_core
datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: remoteuser
    password: RK0FnE7TsiZYHyLxpgJ8iIEtpW7eSnrYe370Y2Wy6XW62c9VpBvQGX7YwByE2Xp8iWdni8lg4b0V+VUZwZCXHQ==
    initialSize: 20
    minIdle: 20
    maxActive: 50
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAILqcyiEIU/xsognRHM+6PX17R0gb+AUgJ75aN+Pn08PNGgTf5Ni4ibD4xGRSZimFSiTut+5nBGE4xMdlBHvKT0CAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
    
sms:
  config:
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}
    product:
      id: 887362


logging:
  level:
    root: info
         
---
spring:
  profiles: uat_93
  redis:
    database: 0
    host: redis
    port: 6393
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10

server:
  port: 8782
  
project:  
  environment: uat
  runmode: singleton
  singleton:
    enterprise: xiaoxue
  checkDataEnable: false
  version: 1.2.2

#oibp_core
datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: remoteuser
    password: RK0FnE7TsiZYHyLxpgJ8iIEtpW7eSnrYe370Y2Wy6XW62c9VpBvQGX7YwByE2Xp8iWdni8lg4b0V+VUZwZCXHQ==
    initialSize: 20
    minIdle: 20
    maxActive: 50
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAILqcyiEIU/xsognRHM+6PX17R0gb+AUgJ75aN+Pn08PNGgTf5Ni4ibD4xGRSZimFSiTut+5nBGE4xMdlBHvKT0CAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
    
sms:
  config:
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}
    product:
      id: 887362


logging:
  level:
    root: info

---
spring:
  profiles: uat_92
  redis:
    database: 0
    host: redis
    port: 6392
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10

server:
  port: 8781
  
project:  
  environment: dev
  runmode: saas
  checkDataEnable: false
  version: 1.4.3

#oibp_core
datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: remoteuser
    password: RK0FnE7TsiZYHyLxpgJ8iIEtpW7eSnrYe370Y2Wy6XW62c9VpBvQGX7YwByE2Xp8iWdni8lg4b0V+VUZwZCXHQ==
    initialSize: 20
    minIdle: 20
    maxActive: 50
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAILqcyiEIU/xsognRHM+6PX17R0gb+AUgJ75aN+Pn08PNGgTf5Ni4ibD4xGRSZimFSiTut+5nBGE4xMdlBHvKT0CAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
    
sms:
  config:
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}
    product:
      id: 887362


logging:
  level:
    root: info
    
---
spring:
  profiles: uat_89
  redis:
    database: 0
    host: redis
    port: 6389
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10

server:
  port: 8980
  
project:  
  environment: dev
  runmode: singleton
  singleton:
    enterprise: xiaobaibai
  checkDataEnable: false
  version: 1.2.2

#oibp_core
datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: remoteuser
    password: RK0FnE7TsiZYHyLxpgJ8iIEtpW7eSnrYe370Y2Wy6XW62c9VpBvQGX7YwByE2Xp8iWdni8lg4b0V+VUZwZCXHQ==
    initialSize: 20
    minIdle: 20
    maxActive: 50
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAILqcyiEIU/xsognRHM+6PX17R0gb+AUgJ75aN+Pn08PNGgTf5Ni4ibD4xGRSZimFSiTut+5nBGE4xMdlBHvKT0CAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
    
sms:
  config:
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}
    product:
      id: 887362


logging:
  level:
    root: info
    
---
spring:
  profiles: uat_saas
  redis:
    database: 0
    host: redis
    port: 6393
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10
   
server:
  port: 8782
     
project:  
  environment: uat
  runmode: saas
  checkDataEnable: false
  version: 1.2.2

#oibp_core
datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: remoteuser
    password: RK0FnE7TsiZYHyLxpgJ8iIEtpW7eSnrYe370Y2Wy6XW62c9VpBvQGX7YwByE2Xp8iWdni8lg4b0V+VUZwZCXHQ==
    initialSize: 20
    minIdle: 20
    maxActive: 50
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAILqcyiEIU/xsognRHM+6PX17R0gb+AUgJ75aN+Pn08PNGgTf5Ni4ibD4xGRSZimFSiTut+5nBGE4xMdlBHvKT0CAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
    
sms:
  config:
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}
    product:
      id: 887362


logging:
  level:
    root: info
     
    
---
spring:
  profiles: prod_singleton  
  redis:
    database: 0
    host: redis
    port: 6379
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10
      
project:  
  environment: prod
  runmode: singleton
  singleton:
    enterprise: demo
  checkDataEnable: false
  version: 1.4.3
  
#oibp_core
datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://oibp-mysql.mysql.rds.aliyuncs.com:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: oibphiadmin
    password: AoHk7V2EH462x3JO2ogQvwjyZZnitxp/faphcesSTUyQmsZ+8Ti3c0oNxVs8vP7z2r9HVstpiSEpdaJyz+8hWA==
    initialSize: 20
    minIdle: 20
    maxActive: 50
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMQbuSuDClsL5vzYwhzAVp+ChicfawZnhpkb+EcXx9M61UXnJPwG8llfzvwhmYF3c0gwsuO2BO2sWWhYQUg66csCAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
        
sms:
  config:    
    product:
      id: 887362
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}

      
logging:
  level:
    root: info

---
spring:
  profiles: prod_saas_professional
  redis:
    database: 0
    host: 172.16.105.113
    port: 6379
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10
      
project:  
  environment: prod
  runmode: saas
  checkDataEnable: false
  version: 1.4.3

#oibp_core
datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://oibp-mysql.mysql.rds.aliyuncs.com:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: oibphiadmin
    password: AoHk7V2EH462x3JO2ogQvwjyZZnitxp/faphcesSTUyQmsZ+8Ti3c0oNxVs8vP7z2r9HVstpiSEpdaJyz+8hWA==
    initialSize: 2
    minIdle: 2
    maxActive: 10
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMQbuSuDClsL5vzYwhzAVp+ChicfawZnhpkb+EcXx9M61UXnJPwG8llfzvwhmYF3c0gwsuO2BO2sWWhYQUg66csCAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
    
sms:
  config:
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}
    product:
      id: 887362


logging:
  level:
    root: info

---
spring:
  profiles: prod_saas_standard
  redis:
    database: 0
    host: 172.16.105.113
    port: 6379
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10
      
project:  
  environment: prod
  runmode: saas
  checkDataEnable: false
  version: 1.2.2

#oibp_core
datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://oibp-mysql.mysql.rds.aliyuncs.com:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: oibphiadmin
    password: AoHk7V2EH462x3JO2ogQvwjyZZnitxp/faphcesSTUyQmsZ+8Ti3c0oNxVs8vP7z2r9HVstpiSEpdaJyz+8hWA==
    initialSize: 2
    minIdle: 2
    maxActive: 10
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMQbuSuDClsL5vzYwhzAVp+ChicfawZnhpkb+EcXx9M61UXnJPwG8llfzvwhmYF3c0gwsuO2BO2sWWhYQUg66csCAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
    
sms:
  config:
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}
    product:
      id: 887362


logging:
  level:
    root: info
    
---
spring:
  profiles: tencent_singleton_90
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: oibp123!@#
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 10
server:
  port: 8090
  
project:  
  environment: dev
  runmode: singleton
  singleton:
    enterprise: huqi
  checkDataEnable: false
  version: 1.2.2
#oibp_core
datasource:
  oibp_core:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.0.10:3306/oibp_core?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: remoteuser
    password: RK0FnE7TsiZYHyLxpgJ8iIEtpW7eSnrYe370Y2Wy6XW62c9VpBvQGX7YwByE2Xp8iWdni8lg4b0V+VUZwZCXHQ==
    initialSize: 20
    minIdle: 20
    maxActive: 50
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAILqcyiEIU/xsognRHM+6PX17R0gb+AUgJ75aN+Pn08PNGgTf5Ni4ibD4xGRSZimFSiTut+5nBGE4xMdlBHvKT0CAwEAAQ==
    bin:
      path: /usr/bin/
  oibp_init:
    name: oibp_init_ent
    
sms:
  config:
    username: oibp
    password: DLzQcqo0IxLsGOpZ6BVNCef64WLUrFpOl538bQFAyJnCHz1ft3B0MYOYeysxHgLSQ0z5Zf6q+oaMOGE6gtI8WQ==
    decryptKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJNI4RFzpE8X5i9Btg6xURhUwCazH9+VDJ+yRYWJZeT5AYEJcp9L5Hg/khWw0L4kpppoAtzQ6YM6W/sGqV2Afj8CAwEAAQ==
    url: http://www.ztsms.cn/sendSms.do?username={username}&password={password}&mobile={mobile}&content={content}&dstime={dstime}&productid={productid}
    product:
      id: 887362
logging:
  level:
    root: info

